# typings/flask_login.pyi
from typing import Any

def login_user(user: Any, remember: bool = ..., duration: Any = ..., force: bool = ..., fresh: bool = ...) -> bool: ...
def logout_user() -> bool: ...
def current_user() -> Any: ...
def login_required(func: Any) -> Any: ...

class LoginManager:
    def __init__(self) -> None: ...
    def init_app(self, app: Any) -> None: ...
    def user_loader(self, callback: Any) -> None: ...

class UserMixin:
    ...
